site_name: Flashreads
theme:
  name: material
  palette:
    primary: light blue
markdown_extensions:
  - meta
  - codehilite
  - admonition
plugins:
  - exclude:
      glob:
        - template.md
      regex:
        - "^[^/]+/(README|readme)\\.(md|MD)$"
        - "^[^/]+/([^/]+/)+(README|readme)\\.(md|MD)$"
