site_name: Flashreads
repo_name: 'flashreads/blogs'
repo_url: 'https://github.com/flashreads/blogs'
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: light blue
markdown_extensions:
  - meta
  - codehilite
  - admonition
  - meta
plugins:
  - exclude:
      glob:
        - template.md
      regex:
        - "^[^/]+/(README|readme)\\.(md|MD)$"
        - "^[^/]+/([^/]+/)+(README|readme)\\.(md|MD)$"
  - git-revision-date-localized